version: '3'
services:

  app:
    build: .
    environment:
      - VIRTUAL_HOST=app.localtest.me

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro